// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nucleus.Repository;

#nullable disable

namespace Nucleus.Migrations
{
    [DbContext(typeof(NucleusDbContext))]
    [Migration("20251102000644_AddMd5HashToClips")]
    partial class AddMd5HashToClips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nucleus.Repository.ApexMapRotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("Gamemode")
                        .HasColumnType("integer")
                        .HasColumnName("gamemode");

                    b.Property<int>("Map")
                        .HasColumnType("integer")
                        .HasColumnName("map");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("apex_map_rotation_pkey");

                    b.ToTable("apex_map_rotation", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.Clip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CategoryEnum")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("clip_pkey");

                    b.ToTable("clip", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.ClipCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CategoryEnum")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("clip_collection_pkey");

                    b.HasIndex(new[] { "OwnerId" }, "ix_clip_collection__owner_id");

                    b.ToTable("clip_collection", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.ClipTag", b =>
                {
                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ClipId", "TagId")
                        .HasName("clip_tag_pkey");

                    b.HasIndex(new[] { "TagId" }, "ix_clip_tag__tag_id");

                    b.ToTable("clip_tag", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.ClipView", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("UserId", "ClipId")
                        .HasName("clip_view_pkey");

                    b.HasIndex(new[] { "ClipId" }, "ix_clip_view__clip_id");

                    b.ToTable("clip_view", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.DiscordUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avatar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avatar");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discord_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("discord_user_pkey");

                    b.HasIndex(new[] { "DiscordId" }, "uq_discord_user_discord_id")
                        .IsUnique();

                    b.ToTable("discord_user", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tag_pkey");

                    b.HasIndex(new[] { "Name" }, "uq_tag__name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.UserFrequentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_frequent_link_pkey");

                    b.HasIndex(new[] { "UserId" }, "ix_user_frequent_link__user_id");

                    b.ToTable("user_frequent_link", (string)null);
                });

            modelBuilder.Entity("Nucleus.Repository.ClipCollection", b =>
                {
                    b.HasOne("Nucleus.Repository.DiscordUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_collection__discord_user");
                });

            modelBuilder.Entity("Nucleus.Repository.ClipTag", b =>
                {
                    b.HasOne("Nucleus.Repository.Clip", "Clip")
                        .WithMany("ClipTags")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_tag__clip");

                    b.HasOne("Nucleus.Repository.Tag", "Tag")
                        .WithMany("ClipTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_tag__tag");

                    b.Navigation("Clip");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Nucleus.Repository.ClipView", b =>
                {
                    b.HasOne("Nucleus.Repository.Clip", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_view__clip");

                    b.HasOne("Nucleus.Repository.DiscordUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_view__user");

                    b.Navigation("Clip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nucleus.Repository.UserFrequentLink", b =>
                {
                    b.HasOne("Nucleus.Repository.DiscordUser", "User")
                        .WithMany("UserFrequentLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_frequent_link__user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nucleus.Repository.Clip", b =>
                {
                    b.Navigation("ClipTags");
                });

            modelBuilder.Entity("Nucleus.Repository.DiscordUser", b =>
                {
                    b.Navigation("UserFrequentLinks");
                });

            modelBuilder.Entity("Nucleus.Repository.Tag", b =>
                {
                    b.Navigation("ClipTags");
                });
#pragma warning restore 612, 618
        }
    }
}
