services:
  nucleus:
    image: nucleus
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:8080
      # Easiest way to honor X-Forwarded-* from Caddy without code changes:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      # Optional: make sure it's Production
      - ASPNETCORE_ENVIRONMENT=Production
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # For HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - nucleus

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: