name: Deploy to VPS

on:
  push:
    branches: [ master ]  # or master, depending on your default branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /Nucleus
          git pull origin master
          cd /Nucleus
          cat > .env << EOF
          ApexLegendsApiKey=${{ secrets.APEXLEGENDSAPIKEY }}
          EOF
          docker-compose down
          docker-compose build
          docker-compose up -d
          docker system prune -f
